# Generated by Django 5.1.5 on 2025-02-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'verbose_name': 'deck', 'verbose_name_plural': 'decks'},
        ),
    ]
