# Generated by Django 5.1.7 on 2025-03-28 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cards', models.PositiveIntegerField(default=0)),
                ('completed_cards', models.PositiveIntegerField(default=0)),
                ('total_decks', models.PositiveIntegerField(default=0)),
                ('completed_decks', models.PositiveIntegerField(default=0)),
                ('completed_decks_percentage', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_statistics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
