# Generated by Django 5.1.7 on 2025-03-31 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userstatistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatistic',
            name='completed_cards',
        ),
        migrations.RemoveField(
            model_name='userstatistic',
            name='total_cards',
        ),
    ]
