# Generated by Django 5.1.7 on 2025-03-31 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userstatistic_completed_cards_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userstatistic',
            table='users_user_statistic',
        ),
    ]
