# Generated by Django 5.2 on 2025-04-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userstatistic_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistic',
            name='completed_decks_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
