services:
  web-app:
    build: .
    env_file: .env
    command: gunicorn src.wsgi:application --bind 0.0.0.0:${APP_PORT}
    volumes:
      - static:/app/src/staticfiles
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine3.21
    hostname: database
    env_file: .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine3.20

  caddy:
    image: caddy:2.9-alpine
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
      - static:/usr/share/caddy/static

  celery-worker:
    build: .
    env_file: .env
    hostname: worker-1
    command: celery -A src worker --loglevel=info
    volumes:
      - ./src/:/app/src/
    depends_on:
      - db
      - redis

volumes:
  data:
  static:
  caddy-data:
  caddy-config: