# Generated by Django 5.1.6 on 2025-02-12 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_answered_alter_card_deck_alter_card_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='answered',
        ),
        migrations.CreateModel(
            name='CardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=False)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_state', to='cards.card')),
            ],
            options={
                'verbose_name': 'card_state',
            },
        ),
    ]
