# Generated by Django 5.1.7 on 2025-03-31 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_card_answered_cardstate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cardstate',
            table='cards_card_state',
        ),
    ]
